---
title: "02_5_DESeq_Gill_LC_genome"
output: html_document
date: "2024-06-14"
---

---
title: "DESeq_Foot_LC"
output: html_document
date: "2024-06-14"
---
```{r load libraries}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.16")

BiocManager::install("DESeq2")
library("DESeq2") # Bioconductor
library("tidyverse")
library("dplyr")
library("pheatmap")
library("RColorBrewer")
library("genefilter") # Bioconductor
library("ggplot2")
library("gplots")
library("limma") # Bioconductor
install.packages("spdep")
library("spdep") 
library("adegenet")
library("tximport") # Bioconductor
BiocManager::install("vsn")
BiocManager::install("tidybulk")
BiocManager::install("goseq")
BiocManager::install("affycoretools")
BiocManager::install("EnhancedVolcano")
BiocManager::install("pcaExplorer")
BiocManager::install("apeglm")
BiocManager::install("PCAtools")
BiocManager::install("DESeq2PCA")
library(pcaExplorer)
library(PCAtools)
```

### OA vs lab control
```{r}
# DEG in the foot after exposure to ocean acidification
GOA_LC_treatmentinfo <- read_delim("output/DEG_lists/Gill/GOA_LC_treatmentinfo.csv", delim = " ")

GOA_LC_countmatrix <- subset(gene_count_matrix, select=(GOA_LC_treatmentinfo$sample.1))
GOA_LC_countmatrix <- data.frame(GOA_LC_countmatrix)
write.table(GOA_LC_countmatrix, file = "output/DEG_lists/Gill/GOA_LC_countmatrix.csv")
#doesn't save correctly, need to figure this out

# Calculate DESeq object
dds1 <- DESeqDataSetFromMatrix(countData = GOA_LC_countmatrix,
                              colData = GOA_LC_treatmentinfo,
                              design = ~ treatment)

dds1 <- DESeq(dds1)
resultsNames(dds1) # lists the coefficients

PCAdata <- plotPCA(vst(dds1), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level = 0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Ocean acidification"), values = c("lightblue", "pink"))+
  guides(color=guide_legend("Treatment"))

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds1) >= 10) >= ncol(GOA_LC_countmatrix)/3
dds1_filt <- dds1[keep,]

```

### OW vs lab control
```{r}

GOW_LC_treatmentinfo <- read_delim("output/DEG_lists/Gill/GOW_LC_treatmentinfo.csv", delim = " ")
                                                                                                      
GOW_LC_countmatrix <- subset(gene_count_matrix, select=(GOW_LC_treatmentinfo$sample.1))
write.table(GOW_LC_countmatrix, file = "output/DEG_lists/Gill/GOW_LC_countmatrix.csv")
#Doesn't work still

# Calculate DESeq object
dds2 <- DESeqDataSetFromMatrix(countData = GOW_LC_countmatrix,
                              colData = GOW_LC_treatmentinfo,
                              design = ~ treatment)

dds2 <- DESeq(dds2)
resultsNames(dds2) # lists the coefficients

PCAdata <- plotPCA(vst(dds2), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Ocean warming"), values = c("lightblue", "sandybrown"))+
  guides(color=guide_legend("Treatment"))


# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds2) >= 10) >= ncol(GOW_LC_countmatrix)/3
dds2_filt <- dds2[keep,]

```

### DO vs lab control
```{r}
GDO_LC_treatmentinfo <- read_delim("output/DEG_lists/Gill/GDO_LC_treatmentinfo.csv", delim = " ")
                                                                                                      
GDO_LC_countmatrix <- subset(gene_count_matrix, select=(GDO_LC_treatmentinfo$sample.1))
write.table(GDO_LC_countmatrix, file = "output/DEG_lists/Gill/GDO_LC_countmatrix.csv")
#still comes out wrong

# Calculate DESeq object
dds3 <- DESeqDataSetFromMatrix(countData = GDO_LC_countmatrix,
                              colData = GDO_LC_treatmentinfo,
                              design = ~ treatment)

dds3 <- DESeq(dds3)
resultsNames(dds3) # lists the coefficients

PCAdata <- plotPCA(vst(dds3), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Hypoxia"), values = c("lightblue", "lightgreen"))+
  guides(color=guide_legend("Treatment"))

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds3) >= 10) >= ncol(GDO_LC_countmatrix)/3
dds3_filt <- dds3[keep,]

```


### treatment control vs lab control
```{r}
# RERUN THE DDS, accidentally overwrote it 
# Filter data
GTC_LC_treatmentinfo <- read_delim("output/DEG_lists/Gill/GTC_LC_treatmentinfo.csv", delim = " ")
                                                                                 
GTC_LC_countmatrix <- subset(gene_count_matrix, select=(GTC_LC_treatmentinfo$sample.1))
write.table(GTC_LC_countmatrix, file = "output/DEG_lists/Gill/GTC_LC_countmatrix.csv")    
#still wrong
GTC_LC_treatmentinfo$day <- as.factor(GTC_LC_treatmentinfo$day)

# Calculate DESeq object
dds8 <- DESeqDataSetFromMatrix(countData = GTC_LC_countmatrix,
                              colData = GTC_LC_treatmentinfo,
                              design = ~ day)

dds8 <- DESeq(dds8)
resultsNames(dds8) # lists the coefficients

PCAdata <- plotPCA(vst(dds8), intgroup = c("day"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=day)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Treatment control"), values = c("lightblue", "lavender"))+
  guides(color=guide_legend("Treatment"))

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <-  rowSums(DESeq2::counts(dds8) >= 10) >= ncol(GTC_LC_countmatrix)/3
dds8_filt <- dds8[keep,]

```
