---
title: "02_5_DESeq_Gill_TC_genome"
output: html_document
date: "2024-06-15"
---

```{r load libraries}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.16")

BiocManager::install("DESeq2")
library("DESeq2") # Bioconductor
library("tidyverse")
library("dplyr")
library("pheatmap")
library("RColorBrewer")
library("genefilter") # Bioconductor
library("ggplot2")
library("gplots")
library("limma") # Bioconductor
install.packages("spdep")
library("spdep") 
library("adegenet")
library("tximport") # Bioconductor
BiocManager::install("vsn")
BiocManager::install("tidybulk")
BiocManager::install("goseq")
BiocManager::install("affycoretools")
BiocManager::install("EnhancedVolcano")
BiocManager::install("pcaExplorer")
BiocManager::install("apeglm")
BiocManager::install("PCAtools")
BiocManager::install("DESeq2PCA")
library(pcaExplorer)
library(PCAtools)
```

### OA vs lab control
```{r}
# DEG in the Gill after exposure to ocean acidification
GOA_TC_treatmentinfo <- read_delim("output/DEG_lists/Gill/GOA_TC_treatmentinfo.csv", delim = " ")

GOA_TC_countmatrix <- subset(gene_count_matrix, select=(GOA_TC_treatmentinfo$sample.1))
GOA_TC_countmatrix <- data.frame(GOA_TC_countmatrix)
write.table(GOA_TC_countmatrix, file = "output/DEG_lists/Gill/GOA_TC_countmatrix.csv")
#doesn't save correctly, need to figure this out

# CaTCulate DESeq object
dds12 <- DESeqDataSetFromMatrix(countData = GOA_TC_countmatrix,
                              colData = GOA_TC_treatmentinfo,
                              design = ~ treatment)

dds12 <- DESeq(dds12)
resultsNames(dds12) # lists the coefficients

PCAdata <- plotPCA(vst(dds12), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level = 0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Treatment control", "Ocean acidification"), values = c("lavender", "pink"))+
  guides(color=guide_legend("Treatment"))

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds12) >= 10) >= ncol(GOA_TC_countmatrix)/3
dds12_filt <- dds12[keep,]

```

### OW vs lab control
```{r}

GOW_TC_treatmentinfo <- read_delim("output/DEG_lists/Gill/GOW_TC_treatmentinfo.csv", delim = " ")
                                                                                                      
GOW_TC_countmatrix <- subset(gene_count_matrix, select=(GOW_TC_treatmentinfo$sample.1))
write.table(GOW_TC_countmatrix, file = "output/DEG_lists/Gill/GOW_TC_countmatrix.csv")
#Doesn't work still

# CaTCulate DESeq object
dds13 <- DESeqDataSetFromMatrix(countData = GOW_TC_countmatrix,
                              colData = GOW_TC_treatmentinfo,
                              design = ~ treatment)

dds13 <- DESeq(dds13)
resultsNames(dds13) # lists the coefficients

PCAdata <- plotPCA(vst(dds13), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Treatment control", "Ocean warming"), values = c("lavender", "sandybrown"))+
  guides(color=guide_legend("Treatment"))


# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds13) >= 10) >= ncol(GOW_TC_countmatrix)/3
dds13_filt <- dds13[keep,]

```

### DO vs lab control
```{r}
GDO_TC_treatmentinfo <- read_delim("output/DEG_lists/Gill/GDO_TC_treatmentinfo.csv", delim = " ")
                                                                                                       
GDO_TC_countmatrix <- subset(gene_count_matrix, select=(GDO_TC_treatmentinfo$sample.1))
write.table(GDO_TC_countmatrix, file = "output/DEG_lists/Gill/GDO_TC_countmatrix.csv")
#still comes out wrong

# CaTCulate DESeq object
dds14 <- DESeqDataSetFromMatrix(countData = GDO_TC_countmatrix,
                              colData = GDO_TC_treatmentinfo,
                              design = ~ treatment)

dds14 <- DESeq(dds14)
resultsNames(dds14) # lists the coefficients

PCAdata <- plotPCA(vst(dds14), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Hypoxia"), values = c("lavender", "lightgreen"))+
  guides(color=guide_legend("Treatment"))

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds14) >= 10) >= ncol(GDO_TC_countmatrix)/3
dds14_filt <- dds14[keep,]

```