---
title: "DESeq_Foot_LC"
output: html_document
date: "2024-06-14"
---
```{r load libraries}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.16")

BiocManager::install("DESeq2")
library("DESeq2") # Bioconductor
library("tidyverse")
library("dplyr")
library("pheatmap")
library("RColorBrewer")
library("genefilter") # Bioconductor
library("ggplot2")
library("gplots")
library("limma") # Bioconductor
install.packages("spdep")
library("spdep") 
library("adegenet")
library("tximport") # Bioconductor
BiocManager::install("vsn")
BiocManager::install("tidybulk")
BiocManager::install("goseq")
BiocManager::install("affycoretools")
BiocManager::install("EnhancedVolcano")
BiocManager::install("pcaExplorer")
BiocManager::install("apeglm")
BiocManager::install("PCAtools")
BiocManager::install("DESeq2PCA")
library(pcaExplorer)
library(PCAtools)
```

### OA vs lab control
```{r}
# DEG in the foot after exposure to ocean acidification
FOA_LC_treatmentinfo <- read_delim("output/DEG_lists/Foot/FOA_LC_treatmentinfo.csv", delim = " ")

FOA_LC_countmatrix <- subset(gene_count_matrix, select=(FOA_LC_treatmentinfo$sample.1))
FOA_LC_countmatrix <- data.frame(FOA_LC_countmatrix)
write.table(FOA_LC_countmatrix, file = "output/DEG_lists/Foot/FOA_LC_countmatrix.csv")
#doesn't save correctly, need to figure this out

# Calculate DESeq object
dds4 <- DESeqDataSetFromMatrix(countData = FOA_LC_countmatrix,
                              colData = FOA_LC_treatmentinfo,
                              design = ~ treatment)

dds4 <- DESeq(dds4)
resultsNames(dds4) # lists the coefficients

PCAdata <- plotPCA(vst(dds4), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level = 0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Ocean acidification"), values = c("blue", "red"))+
  guides(color=guide_legend("Treatment"))

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds4) >= 10) >= ncol(FOA_LC_countmatrix)/3
dds4_filt <- dds4[keep,]

```

### OW vs lab control
```{r}

FOW_LC_treatmentinfo <- read_delim("output/DEG_lists/Foot/FOW_LC_treatmentinfo.csv", delim = " ")
                                                                                                      
FOW_LC_countmatrix <- subset(gene_count_matrix, select=(FOW_LC_treatmentinfo$sample.1))
write.table(FOW_LC_countmatrix, file = "output/DEG_lists/Foot/FOW_LC_countmatrix.csv")
#Doesn't work still

# Calculate DESeq object
dds5 <- DESeqDataSetFromMatrix(countData = FOW_LC_countmatrix,
                              colData = FOW_LC_treatmentinfo,
                              design = ~ treatment)

dds5 <- DESeq(dds5)
resultsNames(dds5) # lists the coefficients

PCAdata <- plotPCA(vst(dds5), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Ocean warming"), values = c("blue", "orange"))+
  guides(color=guide_legend("Treatment"))


# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds5) >= 10) >= ncol(FOW_LC_countmatrix)/3
dds5_filt <- dds5[keep,]

```

### DO vs lab control
```{r}
FDO_LC_treatmentinfo <- read_delim("output/DEG_lists/Foot/FDO_LC_treatmentinfo.csv", delim = " ")
                                                                                                      
FDO_LC_countmatrix <- subset(gene_count_matrix, select=(FDO_LC_treatmentinfo$sample.1))
write.table(FDO_LC_countmatrix, file = "output/DEG_lists/Foot/FDO_LC_countmatrix.csv")
#still comes out wrong

# Calculate DESeq object
dds6 <- DESeqDataSetFromMatrix(countData = FDO_LC_countmatrix,
                              colData = FDO_LC_treatmentinfo,
                              design = ~ treatment)

dds6 <- DESeq(dds6)
resultsNames(dds6) # lists the coefficients

PCAdata <- plotPCA(vst(dds6), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Hypoxia"), values = c("blue", "green"))+
  guides(color=guide_legend("Treatment"))

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds6) >= 10) >= ncol(FDO_LC_countmatrix)/3
dds6_filt <- dds6[keep,]

```


### treatment control vs lab control
```{r}
# RERUN THE DDS, accidentally overwrote it 
# Filter data
FTC_LC_treatmentinfo <- read_delim("output/DEG_lists/Foot/FTC_LC_treatmentinfo.csv", delim = " ")
                                                                                 
FTC_LC_countmatrix <- subset(gene_count_matrix, select=(FTC_LC_treatmentinfo$sample.1))
write.table(FTC_LC_countmatrix, file = "output/DEG_lists/Foot/FTC_LC_countmatrix.csv")    
#still wrong
FTC_LC_treatmentinfo$day <- as.factor(FTC_LC_treatmentinfo$day)

# Calculate DESeq object
dds7 <- DESeqDataSetFromMatrix(countData = FTC_LC_countmatrix,
                              colData = FTC_LC_treatmentinfo,
                              design = ~ day)

dds7 <- DESeq(dds7)
resultsNames(dds7) # lists the coefficients

PCAdata <- plotPCA(vst(dds7), intgroup = c("day"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=day)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Lab control", "Treatment control"), values = c("blue", "purple"))+
  guides(color=guide_legend("Treatment"))

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <-  rowSums(DESeq2::counts(dds7) >= 10) >= ncol(FTC_LC_countmatrix)/3
dds7_filt <- dds7[keep,]

```
