---
title: "Getting_GOSlims"
output: html_document
date: "2024-04-03"
---
## Set GSEAbase location and download `goslim_generic.obo`
```{r download-goslim-obo}
library(GSEABase)
goslims <- "goslim_generic.obo"
goslims_url <- "http://current.geneontology.org/ontology/subsets/goslim_generic.obo"
gseabase_location <- find.package("GSEABase")
goslim_obo_dest <- file.path(gseabase_location, "extdata", goslims, fsep = "/")
download.file(url = goslims_url,
              destfile = goslim_obo_dest)

fl <- system.file("extdata", goslims, package="GSEABase")
```


```{r}

FDO_sigs_ID_cleaned_separated <- separate_rows(FDO_sigs_ID, GO.IDs, sep = ";")

# Vector of GO IDs
FDO_go_ids <- FDO_sigs_ID_cleaned_separated$GO.IDs

# Create custom collection with our GO IDs
FDOmyCollection <- GOCollection(FDO_go_ids)

# Pull out GOslims from GOslim obo file
slim <- getOBOCollection(fl)

# Get Biological Process (BP) GOslims for our GO IDs
slimdf <- goSlim(FDOmyCollection, slim, "BP", verbose)

# Convert to list
gomap <- as.list(GOBPOFFSPRING[rownames(slimdf)])

# Map our GOIDs to GOslims
mapped <- lapply(gomap, intersect, ids(myCollection))

# sapply needed to apply paste() to create semi-colon delimited values
slimdf$ids <- sapply(lapply(gomap, intersect, ids(myCollection)), paste, collapse=";")

# Remove "charcter(0) string from "ids" column
slimdf$ids[slimdf$ids == "character(0)"] <- ""

# Add self-matching GOIDs to "ids" column, if not present
updated_slimdf <- slimdf

for (go_id in go_ids) {
  # Check if the go_id is present in the row names
  if (go_id %in% rownames(updated_slimdf)) {
    # Check if the go_id is not present in the ids column
    # Also removes white space "trimws()" and converts all to upper case to handle
    # any weird, "invisible" formatting issues.
    if (!go_id %in% trimws(toupper(strsplit(updated_slimdf[go_id, "ids"], ";")[[1]]))) {
      # Append the go_id to the ids column with a semi-colon separator
      if (length(updated_slimdf$ids) > 0 && nchar(updated_slimdf$ids[nrow(updated_slimdf)]) > 0) {
        updated_slimdf[go_id, "ids"] <- paste0(updated_slimdf[go_id, "ids"], "; ", go_id)
      } else {
        updated_slimdf[go_id, "ids"] <- go_id
      }
    }
  }
}

str(updated_slimdf)
```


```


