---
title: "DGE_viz"
output: html_document
date: "2024-02-05"
---

## Overall comparison with day zero control
```{r}
treatmentinfo.control2  <- treatmentinfo.2 %>% filter(tissue == "F") %>%
  filter(!( tissue == "G"))

treatmentinfo.control2 <- treatmentinfo.control2 %>%
  mutate(treatment = ifelse(day == "3" & treatment == "control", paste0(treatment, "_3"), treatment))

countmatrix_truecon <- subset(countmatrix_2, select=row.names(treatmentinfo.control2))

dds3 <- DESeqDataSetFromMatrix(countData = countmatrix_truecon,
                              colData = treatmentinfo.control2,
                              design = ~ treatment)

dds3 <- DESeq(dds3)
resultsNames(dds3) # lists the coefficients
summary(dds3)

PCAdata <- plotPCA(vst(dds3), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse()

```

OA vs true control
```{r}
# DEG in the foot after exposure to ocean acidification

# Filter data
treatmentinfo.FOA <- treatmentinfo.2 %>% filter(tissue == "F" | treatment == "control" | treatment == "OA") %>% filter(!(tissue == "G" | treatment == "OW" | treatment == "DO"))
                                                                                                      treatmentinfo.FOA <- treatmentinfo.FOA %>%
  filter(!(treatment == "control" & day == "3")) 
                                                                                                      
countmatrix_FOA <- subset(countmatrix_2, select=row.names(treatmentinfo.FOA))

# Calculate DESeq object
dds4 <- DESeqDataSetFromMatrix(countData = countmatrix_FOA,
                              colData = treatmentinfo.FOA,
                              design = ~ treatment)

dds4 <- DESeq(dds4)
resultsNames(dds4) # lists the coefficients

PCAdata <- plotPCA(vst(dds4), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse()

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds4) >= 10) >= ncol(countmatrix_FOA)/3
dds4_filt <- dds4[keep,]

# Generate Contrasts
contrast_listOA    <- c("treatment", "OA", "control") # order is important: factor, treatment group, control
res_tableOA        <- results(dds4_filt, contrast=contrast_listOA, alpha = 0.05)

res_tableOA
```

OW vs true control
```{r}

# Filter data
treatmentinfo.FOW <- treatmentinfo.2 %>% filter(tissue == "F" | treatment == "control" | treatment == "OW") %>% filter(!(tissue == "G" | treatment == "OA" | treatment == "DO"))
                                                                                                    treatmentinfo.FOW <- treatmentinfo.FOW %>%
  filter(!(treatment == "control" & day == "3")) 
                                                                                                      
countmatrix_FOW <- subset(countmatrix_2, select=row.names(treatmentinfo.FOW))

# Calculate DESeq object
dds5 <- DESeqDataSetFromMatrix(countData = countmatrix_FOW,
                              colData = treatmentinfo.FOW,
                              design = ~ treatment)

dds5 <- DESeq(dds5)
resultsNames(dds5) # lists the coefficients

PCAdata <- plotPCA(vst(dds5), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds5) >= 10) >= ncol(countmatrix_FOW)/3
dds5_filt <- dds5[keep,]

# Generate Contrasts
contrast_listOW    <- c("treatment", "OW", "control") # order is important: factor, treatment group, control
res_tableFOW        <- results(dds5_filt, contrast=contrast_listOW, alpha = 0.05)

res_tableFOW
```

## DO vs true control
```{r}

# Filter data
treatmentinfo.FDO <- treatmentinfo.2 %>% filter(tissue == "F" | treatment == "control" | treatment == "DO") %>% filter(!(tissue == "G" | treatment == "OA" | treatment == "OW"))
                                                                                                    treatmentinfo.FDO <- treatmentinfo.FDO %>%
  filter(!(treatment == "control" & day == "3")) 
                                                                                                      
countmatrix_FDO <- subset(countmatrix_2, select=row.names(treatmentinfo.FDO))

# Calculate DESeq object
dds6 <- DESeqDataSetFromMatrix(countData = countmatrix_FDO,
                              colData = treatmentinfo.FDO,
                              design = ~ treatment)

dds6 <- DESeq(dds6)
resultsNames(dds6) # lists the coefficients

PCAdata <- plotPCA(vst(dds6), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds6) >= 10) >= ncol(countmatrix_FDO)/3
dds6_filt <- dds6[keep,]

# Generate Contrasts
contrast_listDO    <- c("treatment", "DO", "control") # order is important: factor, treatment group, control
res_tableFDO        <- results(dds6_filt, contrast=contrast_listDO, alpha = 0.05)

res_tableFDO
```


## Control day 3 vs true control
```{r}
# RERUN THE DDS, accidentally overwrote it 
# Filter data
treatmentinfo.Fcon <- treatmentinfo.2 %>% filter(tissue == "F" | treatment == "control") %>% filter(!(tissue == "G" | treatment == "OA" | treatment == "OW" | treatment == "DO"))
                                                                                                  
countmatrix_Fcon <- subset(countmatrix_2, select=row.names(treatmentinfo.Fcon))

# Calculate DESeq object
dds7 <- DESeqDataSetFromMatrix(countData = countmatrix_Fcon,
                              colData = treatmentinfo.Fcon,
                              design = ~ day)

dds7 <- DESeq(dds7)
resultsNames(dds7) # lists the coefficients

PCAdata <- plotPCA(vst(dds7), intgroup = c("day"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=day)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse()

# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <-  rowSums(DESeq2::counts(dds7) >= 10) >= ncol(countmatrix_Fcon)/3
dds7_filt <- dds7[keep,]

# Generate Contrasts
contrast_listcon    <- c("day", "3", "0") # order is important: factor, treatment group, control
res_tableconF        <- results(dds7_filt, contrast=contrast_listcon, alpha = 0.05)

res_tableconF
```
