---
title: "Comparing gene tables"
output: html_document
date: "2024-02-20"
---

### Load libraries
```{r load_libraries, inlcude = TRUE}
## clear
rm(list=ls())
# List of packages we want to install (run every time)
load.lib<-c("RColorBrewer","readxl","ggpubr","tidyverse","tibble","stringr","beepr","gplots")
# Select only the packages that aren't currently installed (run every time)
install.lib <- load.lib[!load.lib %in% installed.packages()]
# And finally we install the missing packages, including their dependency.
for(lib in install.lib) install.packages(lib,dependencies=TRUE)
# After the installation process completes, we load all packages.
sapply(load.lib,require,character=TRUE)

#invisible(lapply(paste0('package:', names(sessionInfo()$otherPkgs)), detach, character.only=TRUE, unload=TRUE))

library(tidyverse)
library(dplyr)
```

### FDO merge (THIS MIGHT BE WRONG, MIGHT NEED TO MERGE TC INTO LC)
```{r}
FDO_TC_siggene <- read.delim("output/DEG_lists/Foot/FDO_TC_siggene.csv", sep = " ", header = TRUE)
FDO_LC_siggene <- read.delim("output/DEG_lists/Foot/FDO_LC_siggene_apeglm.csv", sep = " ", header = TRUE)

FDO_sigs <- inner_join(FDO_TC_siggene, FDO_LC_siggene, by = 'gene')
#basemean x is TC, basemean y is LC

FDO_sigs$log2FoldChange <- FDO_sigs$log2FoldChange.x-FDO_sigs$log2FoldChange.y
FDO_sigs_inter <- FDO_sigs[,c(1,12)]

# Merge dataframes based on the shared column 'ID' and replace values from df2 into df1
FDO_sigs_merged <- merge(FDO_TC_siggene, FDO_sigs_inter, by = "gene", all.x = TRUE)

# Replace values in df_y with values from df_x based on a condition
FDO_sigs_merged$log2FoldChange.x <- ifelse(!is.na(FDO_sigs_merged$log2FoldChange.y) , FDO_sigs_merged$log2FoldChange.y, FDO_sigs_merged$log2FoldChange.x)

# Drop the extra column "Value_x" if needed
FDO_sigs_merged <- FDO_sigs_merged[, !(names(FDO_sigs_merged) %in% c("log2FoldChange.y"))]

```

### GDO merge
```{r}
GDO_TC_siggene <- read.delim("output/DEG_lists/Gill/GDO_TC_siggene.csv", sep = " ", header = TRUE)
GDO_LC_siggene <- read.delim("output/DEG_lists/Gill/GDO_LC_siggene_apeglm.csv", sep = " ", header = TRUE)

GDO_sigs <- inner_join(GDO_TC_siggene, GDO_LC_siggene, by = 'gene')
#basemean x is TC, basemean y is LC

GDO_sigs$log2FoldChange <- GDO_sigs$log2FoldChange.x-GDO_sigs$log2FoldChange.y
GDO_sigs_inter <- GDO_sigs[,c(1,12)]

# Merge dataframes based on the shared column 'ID' and replace values from df2 into df1
GDO_sigs_merged <- merge(GDO_TC_siggene, GDO_sigs_inter, by = "gene", all.x = TRUE)

# Replace values in df_y with values from df_x based on a condition
GDO_sigs_merged$log2FoldChange.x <- ifelse(!is.na(GDO_sigs_merged$log2FoldChange.y) , GDO_sigs_merged$log2FoldChange.y, GDO_sigs_merged$log2FoldChange.x)

# Drop the extra column "Value_x" if needed
GDO_sigs_merged <- GDO_sigs_merged[, !(names(GDO_sigs_merged) %in% c("log2FoldChange.y"))]

```

